import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Subject: React.FC<{subject: string; exams: string[]}> = ({subject, exams}) => {

  return (
    <div className="border-solid border flex flex-col justify-center border-white rounded-md my-2 p-2">
      <div className="text-lg text-center mb-2">{subject}</div>
      <div className="flex flex-col justify-center mx-auto">{exams.map((exam) => (
        <span key={`${subject}-${exam}`}>|-&gt;<a href={`/questions?subject=${subject}&exam=${exam}`}>{exam}</a></span>
      ))}</div>
    </div>
  );
}

const Home: NextPage = () => {
  const {data, isLoading} = trpc.useQuery(["exams.get-subject-exams-tree"]);

  if (!data || isLoading) {
    return <div>Loading...</div>;
  }

  return (
    <>
      <Head>
        <title>Maturalac Next.js App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <>
          <div>Javni ispiti</div>
          {data.map((subject) => (<Subject key={subject.id} subject={subject.subject} exams={subject.exams} />))}
        </>
      </main>
    </>
  );
};

export default Home;
